-- ServeYourself: punto de venta, cocina, equipo, mesas y menu publico con QR.
-- Ejecutar despues de 003_mercado_pago_marketplace.sql.

begin;

create table if not exists public.restaurant_staff (
    id bigint generated by default as identity primary key,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    staff_role text not null check (staff_role in ('waiter', 'kitchen', 'manager')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (restaurant_id, user_id)
);

create table if not exists public.restaurant_staff_invites (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    code text not null unique,
    staff_role text not null check (staff_role in ('waiter', 'kitchen', 'manager')),
    created_by uuid not null references auth.users(id) on delete cascade,
    expires_at timestamptz not null default (now() + interval '48 hours'),
    used_by uuid references auth.users(id) on delete set null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.restaurant_tables (
    id bigint generated by default as identity primary key,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    name text not null check (char_length(trim(name)) between 1 and 40),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create unique index if not exists restaurant_tables_unique_name
    on public.restaurant_tables (restaurant_id, lower(name));

alter table public.orders
    add column if not exists order_source text not null default 'online',
    add column if not exists service_type text not null default 'pickup',
    add column if not exists table_id bigint references public.restaurant_tables(id) on delete set null,
    add column if not exists created_by uuid references auth.users(id) on delete set null,
    add column if not exists waiter_name text,
    add column if not exists closed_at timestamptz;

alter table public.orders drop constraint if exists orders_order_source_check;
alter table public.orders add constraint orders_order_source_check
    check (order_source in ('online', 'pos'));

alter table public.orders drop constraint if exists orders_service_type_check;
alter table public.orders add constraint orders_service_type_check
    check (service_type in ('pickup', 'dine_in'));

alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check
    check (payment_method in ('cash', 'transfer', 'mercado_pago', 'card_terminal'));

alter table public.restaurant_staff enable row level security;
alter table public.restaurant_staff_invites enable row level security;
alter table public.restaurant_tables enable row level security;

create or replace function public.has_restaurant_access(
    p_restaurant_id uuid,
    p_roles text[] default array['waiter', 'kitchen', 'manager']::text[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.id = p_restaurant_id and p.role = 'negocio'
    ) or exists (
        select 1 from public.restaurant_staff s
        where s.restaurant_id = p_restaurant_id
          and s.user_id = auth.uid()
          and s.is_active
          and s.staff_role = any(p_roles)
    );
$$;

revoke all on function public.has_restaurant_access(uuid, text[]) from public, anon;
grant execute on function public.has_restaurant_access(uuid, text[]) to authenticated;

drop policy if exists "staff_read" on public.restaurant_staff;
create policy "staff_read" on public.restaurant_staff for select to authenticated
using (user_id = auth.uid() or public.has_restaurant_access(restaurant_id, array['manager']));

drop policy if exists "staff_owner_manage" on public.restaurant_staff;
create policy "staff_owner_manage" on public.restaurant_staff for all to authenticated
using (restaurant_id = auth.uid())
with check (restaurant_id = auth.uid());

drop policy if exists "staff_invites_owner" on public.restaurant_staff_invites;
create policy "staff_invites_owner" on public.restaurant_staff_invites for all to authenticated
using (restaurant_id = auth.uid())
with check (restaurant_id = auth.uid() and created_by = auth.uid());

drop policy if exists "tables_staff_read" on public.restaurant_tables;
create policy "tables_staff_read" on public.restaurant_tables for select to authenticated
using (public.has_restaurant_access(restaurant_id));

drop policy if exists "tables_management" on public.restaurant_tables;
create policy "tables_management" on public.restaurant_tables for all to authenticated
using (public.has_restaurant_access(restaurant_id, array['manager']))
with check (public.has_restaurant_access(restaurant_id, array['manager']));

grant select on public.restaurant_staff, public.restaurant_tables to authenticated;
grant insert, update, delete on public.restaurant_tables to authenticated;
grant usage, select on sequence public.restaurant_tables_id_seq to authenticated;

drop policy if exists "orders_read_participants" on public.orders;
create policy "orders_read_participants" on public.orders for select to authenticated
using (
    customer_id = auth.uid()
    or restaurant_id = auth.uid()
    or public.has_restaurant_access(restaurant_id)
);

drop policy if exists "orders_update_restaurant" on public.orders;
create policy "orders_update_restaurant" on public.orders for update to authenticated
using (public.has_restaurant_access(restaurant_id, array['kitchen', 'manager']))
with check (
    public.has_restaurant_access(restaurant_id, array['kitchen', 'manager'])
    and status in ('pendiente', 'preparando', 'listo', 'entregado', 'cancelado')
);

-- Devuelve el restaurante y rol con el que debe abrirse la sesion del usuario.
create or replace function public.get_my_restaurant_access()
returns table (restaurant_id uuid, staff_role text, business_name text)
language sql
stable
security definer
set search_path = ''
as $$
    select access.restaurant_id, access.staff_role, access.business_name
    from (
        select p.id as restaurant_id, 'owner'::text as staff_role, p.business_name, 0 as priority
        from public.profiles p
        where p.id = auth.uid() and p.role = 'negocio'
        union all
        select s.restaurant_id, s.staff_role, p.business_name, 1 as priority
        from public.restaurant_staff s
        join public.profiles p on p.id = s.restaurant_id
        where s.user_id = auth.uid() and s.is_active
    ) access
    order by access.priority, access.staff_role
    limit 1;
$$;

revoke all on function public.get_my_restaurant_access() from public, anon;
grant execute on function public.get_my_restaurant_access() to authenticated;

create or replace function public.create_staff_invite(p_staff_role text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_code text;
    v_invite public.restaurant_staff_invites%rowtype;
begin
    if p_staff_role not in ('waiter', 'kitchen', 'manager') then
        raise exception 'Rol de personal invalido';
    end if;
    if not exists (select 1 from public.profiles where id = v_user_id and role = 'negocio') then
        raise exception 'Solo el propietario puede invitar personal';
    end if;
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    insert into public.restaurant_staff_invites (restaurant_id, code, staff_role, created_by)
    values (v_user_id, v_code, p_staff_role, v_user_id)
    returning * into v_invite;
    return jsonb_build_object('code', v_invite.code, 'role', v_invite.staff_role, 'expires_at', v_invite.expires_at);
end;
$$;

revoke all on function public.create_staff_invite(text) from public, anon;
grant execute on function public.create_staff_invite(text) to authenticated;

create or replace function public.accept_staff_invite(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_invite public.restaurant_staff_invites%rowtype;
    v_business_name text;
begin
    if v_user_id is null then raise exception 'Debes iniciar sesion'; end if;
    select * into v_invite
    from public.restaurant_staff_invites
    where code = upper(trim(p_code)) and used_at is null and expires_at > now()
    for update;
    if not found then raise exception 'El codigo no existe, ya fue usado o vencio'; end if;
    if v_invite.restaurant_id = v_user_id then raise exception 'El propietario no necesita una invitacion'; end if;

    insert into public.restaurant_staff (restaurant_id, user_id, staff_role, is_active)
    values (v_invite.restaurant_id, v_user_id, v_invite.staff_role, true)
    on conflict (restaurant_id, user_id) do update
        set staff_role = excluded.staff_role, is_active = true;

    update public.restaurant_staff_invites
    set used_by = v_user_id, used_at = now()
    where id = v_invite.id;

    select business_name into v_business_name from public.profiles where id = v_invite.restaurant_id;
    return jsonb_build_object(
        'restaurant_id', v_invite.restaurant_id,
        'business_name', v_business_name,
        'staff_role', v_invite.staff_role
    );
end;
$$;

revoke all on function public.accept_staff_invite(text) from public, anon;
grant execute on function public.accept_staff_invite(text) to authenticated;

create or replace function public.list_restaurant_staff()
returns table (id bigint, user_id uuid, full_name text, email text, staff_role text, is_active boolean, created_at timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
    select s.id, s.user_id, p.full_name, p.email, s.staff_role, s.is_active, s.created_at
    from public.restaurant_staff s
    join public.profiles p on p.id = s.user_id
    where s.restaurant_id = auth.uid()
    order by s.created_at desc;
$$;

revoke all on function public.list_restaurant_staff() from public, anon;
grant execute on function public.list_restaurant_staff() to authenticated;

create or replace function public.set_staff_active(p_staff_id bigint, p_is_active boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    update public.restaurant_staff
    set is_active = p_is_active
    where id = p_staff_id and restaurant_id = auth.uid();
    if not found then raise exception 'Integrante no encontrado'; end if;
end;
$$;

revoke all on function public.set_staff_active(bigint, boolean) from public, anon;
grant execute on function public.set_staff_active(bigint, boolean) to authenticated;

create or replace function public.create_pos_order(
    p_restaurant_id uuid,
    p_items jsonb,
    p_notes text default null,
    p_service_type text default 'pickup',
    p_table_id bigint default null,
    p_payment_method text default 'cash'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_restaurant public.profiles%rowtype;
    v_creator public.profiles%rowtype;
    v_item jsonb;
    v_product public.products%rowtype;
    v_quantity integer;
    v_items jsonb := '[]'::jsonb;
    v_total numeric := 0;
    v_order public.orders%rowtype;
begin
    if not public.has_restaurant_access(p_restaurant_id, array['waiter', 'manager']) then
        raise exception 'No tienes permiso para registrar ventas';
    end if;
    if p_service_type not in ('pickup', 'dine_in') then raise exception 'Tipo de servicio invalido'; end if;
    if p_payment_method not in ('cash', 'transfer', 'card_terminal') then
        raise exception 'Metodo de pago invalido';
    end if;
    if p_service_type = 'dine_in' then
        if p_table_id is null or not exists (
            select 1 from public.restaurant_tables
            where id = p_table_id and restaurant_id = p_restaurant_id and is_active
        ) then raise exception 'Selecciona una mesa activa'; end if;
    else
        p_table_id := null;
    end if;
    if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50 then
        raise exception 'El pedido debe contener entre 1 y 50 productos';
    end if;

    select * into v_restaurant from public.profiles where id = p_restaurant_id and role = 'negocio';
    select * into v_creator from public.profiles where id = v_user_id;
    for v_item in select value from jsonb_array_elements(p_items)
    loop
        if coalesce(v_item ->> 'qty', '') !~ '^[0-9]+$' then raise exception 'Cantidad invalida'; end if;
        v_quantity := (v_item ->> 'qty')::integer;
        if v_quantity < 1 or v_quantity > 50 then raise exception 'Cantidad invalida'; end if;
        select * into v_product from public.products
        where id::text = v_item ->> 'id' and restaurant_id = p_restaurant_id and is_available;
        if not found then raise exception 'Un producto ya no esta disponible'; end if;
        v_items := v_items || jsonb_build_array(jsonb_build_object(
            'id', v_product.id, 'nombre', v_product.name, 'price', v_product.price, 'qty', v_quantity
        ));
        v_total := v_total + v_product.price * v_quantity;
    end loop;

    insert into public.orders (
        customer_id, restaurant_id, restaurant_name, items, total, notes, status,
        payment_method, payment_status, order_source, service_type, table_id, created_by, waiter_name
    ) values (
        null, p_restaurant_id, v_restaurant.business_name, v_items, round(v_total, 2),
        nullif(left(trim(coalesce(p_notes, '')), 500), ''), 'pendiente', p_payment_method,
        'approved',
        'pos', p_service_type, p_table_id, v_user_id, v_creator.full_name
    ) returning * into v_order;
    return to_jsonb(v_order);
end;
$$;

revoke all on function public.create_pos_order(uuid, jsonb, text, text, bigint, text) from public, anon;
grant execute on function public.create_pos_order(uuid, jsonb, text, text, bigint, text) to authenticated;

create or replace function public.update_kitchen_order_status(p_order_id bigint, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_order public.orders%rowtype;
begin
    select * into v_order from public.orders where id = p_order_id for update;
    if not found then raise exception 'Pedido no encontrado'; end if;
    if not public.has_restaurant_access(v_order.restaurant_id, array['kitchen', 'manager']) then
        raise exception 'No tienes permiso para actualizar cocina';
    end if;
    if p_status not in ('preparando', 'listo', 'entregado') then raise exception 'Estado invalido'; end if;
    if (v_order.status = 'pendiente' and p_status <> 'preparando')
       or (v_order.status = 'preparando' and p_status <> 'listo')
       or (v_order.status = 'listo' and p_status <> 'entregado') then
        raise exception 'El cambio de estado no es valido';
    end if;
    update public.orders set
        status = p_status,
        ready_at = case when p_status = 'listo' then now() else ready_at end,
        delivered_at = case when p_status = 'entregado' then now() else delivered_at end,
        closed_at = case when p_status = 'entregado' then now() else closed_at end
    where id = p_order_id returning * into v_order;
    return to_jsonb(v_order);
end;
$$;

revoke all on function public.update_kitchen_order_status(bigint, text) from public, anon;
grant execute on function public.update_kitchen_order_status(bigint, text) to authenticated;

-- Vistas publicas deliberadamente limitadas para el menu consultado desde el QR.
drop view if exists public.public_qr_products;
drop view if exists public.public_qr_restaurants;
create view public.public_qr_restaurants as
select id, business_name, address, open_time, close_time, avatar_url, rating, timezone, accepting_orders
from public.profiles where role = 'negocio';

create view public.public_qr_products as
select id, restaurant_id, name, price, category, image_url
from public.products where is_available = true;

revoke all on public.public_qr_restaurants, public.public_qr_products from public;
grant select on public.public_qr_restaurants, public.public_qr_products to anon, authenticated;

commit;
