-- Suite operativa: cuentas abiertas, caja, auditoria, estaciones, inventario,
-- promociones, reservaciones y lealtad.
-- Ejecutar despues de 007_staff_permissions_and_cashier.sql.

begin;

alter table public.orders
    add column if not exists discount_total numeric(12,2) not null default 0,
    add column if not exists tip_total numeric(12,2) not null default 0,
    add column if not exists inventory_deducted boolean not null default false,
    add column if not exists cancelled_reason text;

alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check
    check (payment_method in ('cash', 'transfer', 'mercado_pago', 'card_terminal', 'mixed'));

create table if not exists public.cash_shifts (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    opened_by uuid not null references auth.users(id) on delete restrict,
    opened_at timestamptz not null default now(),
    opening_cash numeric(12,2) not null default 0 check (opening_cash >= 0),
    status text not null default 'open' check (status in ('open', 'closed')),
    closed_by uuid references auth.users(id) on delete set null,
    closed_at timestamptz,
    counted_cash numeric(12,2),
    expected_cash numeric(12,2),
    difference numeric(12,2),
    notes text
);
create unique index if not exists cash_shifts_one_open
    on public.cash_shifts(restaurant_id) where status = 'open';

create table if not exists public.cash_movements (
    id bigint generated by default as identity primary key,
    shift_id uuid not null references public.cash_shifts(id) on delete cascade,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    movement_type text not null check (movement_type in ('income', 'expense')),
    amount numeric(12,2) not null check (amount > 0),
    reason text not null check (char_length(trim(reason)) between 2 and 200),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now()
);

create table if not exists public.order_payments (
    id uuid primary key default gen_random_uuid(),
    order_id bigint not null references public.orders(id) on delete cascade,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    shift_id uuid references public.cash_shifts(id) on delete set null,
    payment_method text not null check (payment_method in ('cash', 'transfer', 'card_terminal')),
    amount numeric(12,2) not null check (amount > 0),
    tip_amount numeric(12,2) not null default 0 check (tip_amount >= 0),
    received_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now()
);

create table if not exists public.order_audit_logs (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    action text not null,
    reason text,
    details jsonb not null default '{}'::jsonb,
    actor_id uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now()
);

create table if not exists public.kitchen_stations (
    id bigint generated by default as identity primary key,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    name text not null check (char_length(trim(name)) between 2 and 40),
    color text not null default '#f97316',
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (restaurant_id, name)
);

create table if not exists public.order_station_statuses (
    order_id bigint not null references public.orders(id) on delete cascade,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    station_key text not null,
    kitchen_station_id bigint references public.kitchen_stations(id) on delete set null,
    status text not null default 'pendiente' check (status in ('pendiente','preparando','listo','entregado')),
    updated_at timestamptz not null default now(),
    primary key (order_id, station_key)
);

alter table public.products
    add column if not exists kitchen_station_id bigint references public.kitchen_stations(id) on delete set null;

drop policy if exists "products_read" on public.products;
create policy "products_read" on public.products for select to authenticated
using (is_available = true or restaurant_id = auth.uid() or public.has_restaurant_access(restaurant_id));

create table if not exists public.ingredients (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    name text not null check (char_length(trim(name)) between 2 and 80),
    unit text not null check (unit in ('pieza', 'g', 'kg', 'ml', 'l')),
    stock numeric(14,3) not null default 0,
    minimum_stock numeric(14,3) not null default 0,
    unit_cost numeric(12,2) not null default 0,
    updated_at timestamptz not null default now(),
    unique (restaurant_id, name)
);

create table if not exists public.product_recipes (
    product_id uuid not null references public.products(id) on delete cascade,
    ingredient_id uuid not null references public.ingredients(id) on delete cascade,
    quantity numeric(14,3) not null check (quantity > 0),
    primary key (product_id, ingredient_id)
);

create table if not exists public.inventory_movements (
    id bigint generated by default as identity primary key,
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    ingredient_id uuid not null references public.ingredients(id) on delete cascade,
    movement_type text not null check (movement_type in ('purchase', 'sale', 'adjustment', 'waste')),
    quantity numeric(14,3) not null,
    reason text,
    order_id bigint references public.orders(id) on delete set null,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.coupons (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    code text not null,
    discount_type text not null check (discount_type in ('percent', 'fixed')),
    discount_value numeric(12,2) not null check (discount_value > 0),
    starts_at timestamptz,
    ends_at timestamptz,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);
create unique index if not exists coupons_unique_code on public.coupons(restaurant_id, upper(code));

create table if not exists public.reservations (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    customer_name text not null,
    phone text not null,
    party_size integer not null check (party_size between 1 and 100),
    reserved_at timestamptz not null,
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'seated', 'completed', 'cancelled')),
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists public.loyalty_customers (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null references public.profiles(id) on delete cascade,
    customer_name text not null,
    phone text not null,
    points integer not null default 0 check (points >= 0),
    visits integer not null default 0 check (visits >= 0),
    updated_at timestamptz not null default now(),
    unique (restaurant_id, phone)
);

alter table public.cash_shifts enable row level security;
alter table public.cash_movements enable row level security;
alter table public.order_payments enable row level security;
alter table public.order_audit_logs enable row level security;
alter table public.kitchen_stations enable row level security;
alter table public.order_station_statuses enable row level security;
alter table public.ingredients enable row level security;
alter table public.product_recipes enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.coupons enable row level security;
alter table public.reservations enable row level security;
alter table public.loyalty_customers enable row level security;

-- Lectura operativa; las escrituras sensibles pasan por RPC o quedan limitadas al propietario.
drop policy if exists "cash_shifts_read" on public.cash_shifts;
create policy "cash_shifts_read" on public.cash_shifts for select to authenticated
using (public.has_restaurant_permission(restaurant_id, 'close_accounts'));
drop policy if exists "cash_movements_read" on public.cash_movements;
create policy "cash_movements_read" on public.cash_movements for select to authenticated
using (public.has_restaurant_permission(restaurant_id, 'close_accounts'));
drop policy if exists "order_payments_read" on public.order_payments;
create policy "order_payments_read" on public.order_payments for select to authenticated
using (public.has_restaurant_permission(restaurant_id, 'close_accounts'));
drop policy if exists "audit_owner_read" on public.order_audit_logs;
create policy "audit_owner_read" on public.order_audit_logs for select to authenticated
using (restaurant_id = auth.uid());
drop policy if exists "stations_staff_read" on public.kitchen_stations;
create policy "stations_staff_read" on public.kitchen_stations for select to authenticated
using (public.has_restaurant_access(restaurant_id));
drop policy if exists "stations_owner_manage" on public.kitchen_stations;
create policy "stations_owner_manage" on public.kitchen_stations for all to authenticated
using (restaurant_id = auth.uid()) with check (restaurant_id = auth.uid());
drop policy if exists "order_stations_staff_read" on public.order_station_statuses;
create policy "order_stations_staff_read" on public.order_station_statuses for select to authenticated
using (public.has_restaurant_permission(restaurant_id, 'view_kitchen'));
drop policy if exists "ingredients_owner" on public.ingredients;
create policy "ingredients_owner" on public.ingredients for all to authenticated
using (restaurant_id = auth.uid()) with check (restaurant_id = auth.uid());
drop policy if exists "recipes_owner" on public.product_recipes;
create policy "recipes_owner" on public.product_recipes for all to authenticated
using (exists (select 1 from public.products p where p.id = product_id and p.restaurant_id = auth.uid()))
with check (exists (select 1 from public.products p where p.id = product_id and p.restaurant_id = auth.uid()));
drop policy if exists "inventory_owner" on public.inventory_movements;
create policy "inventory_owner" on public.inventory_movements for select to authenticated
using (restaurant_id = auth.uid());
drop policy if exists "coupons_owner" on public.coupons;
create policy "coupons_owner" on public.coupons for all to authenticated
using (restaurant_id = auth.uid()) with check (restaurant_id = auth.uid());
drop policy if exists "reservations_owner" on public.reservations;
create policy "reservations_owner" on public.reservations for all to authenticated
using (restaurant_id = auth.uid()) with check (restaurant_id = auth.uid());
drop policy if exists "loyalty_owner" on public.loyalty_customers;
create policy "loyalty_owner" on public.loyalty_customers for all to authenticated
using (restaurant_id = auth.uid()) with check (restaurant_id = auth.uid());
grant select on public.cash_shifts, public.cash_movements, public.order_payments,
    public.order_audit_logs, public.kitchen_stations, public.ingredients,
    public.order_station_statuses, public.product_recipes, public.inventory_movements, public.coupons,
    public.reservations, public.loyalty_customers to authenticated;
grant insert, update, delete on public.kitchen_stations, public.ingredients,
    public.product_recipes, public.coupons, public.reservations,
    public.loyalty_customers to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.open_cash_shift(p_restaurant_id uuid, p_opening_cash numeric)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_shift public.cash_shifts%rowtype;
begin
    if not public.has_restaurant_permission(p_restaurant_id, 'close_accounts') then raise exception 'Sin permiso de caja'; end if;
    if p_opening_cash < 0 then raise exception 'El fondo inicial no puede ser negativo'; end if;
    insert into public.cash_shifts(restaurant_id, opened_by, opening_cash)
    values (p_restaurant_id, auth.uid(), p_opening_cash) returning * into v_shift;
    return to_jsonb(v_shift);
exception when unique_violation then raise exception 'Ya existe un turno de caja abierto';
end; $$;

create or replace function public.add_cash_movement(p_restaurant_id uuid, p_type text, p_amount numeric, p_reason text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_shift public.cash_shifts%rowtype; v_movement public.cash_movements%rowtype;
begin
    if not public.has_restaurant_permission(p_restaurant_id, 'close_accounts') then raise exception 'Sin permiso de caja'; end if;
    if p_type not in ('income','expense') or p_amount <= 0 or char_length(trim(p_reason)) < 2 then raise exception 'Movimiento invalido'; end if;
    select * into v_shift from public.cash_shifts where restaurant_id = p_restaurant_id and status = 'open' for update;
    if not found then raise exception 'Primero abre un turno de caja'; end if;
    insert into public.cash_movements(shift_id, restaurant_id, movement_type, amount, reason, created_by)
    values(v_shift.id, p_restaurant_id, p_type, p_amount, left(trim(p_reason),200), auth.uid()) returning * into v_movement;
    return to_jsonb(v_movement);
end; $$;

create or replace function public.close_cash_shift(p_restaurant_id uuid, p_counted_cash numeric, p_notes text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_shift public.cash_shifts%rowtype; v_cash_sales numeric := 0; v_movements numeric := 0; v_expected numeric;
begin
    if not public.has_restaurant_permission(p_restaurant_id, 'close_accounts') then raise exception 'Sin permiso de caja'; end if;
    if p_counted_cash < 0 then raise exception 'El efectivo contado no puede ser negativo'; end if;
    select * into v_shift from public.cash_shifts where restaurant_id = p_restaurant_id and status = 'open' for update;
    if not found then raise exception 'No hay turno abierto'; end if;
    select coalesce(sum(amount + tip_amount),0) into v_cash_sales from public.order_payments where shift_id = v_shift.id and payment_method = 'cash';
    select coalesce(sum(case when movement_type='income' then amount else -amount end),0) into v_movements from public.cash_movements where shift_id = v_shift.id;
    v_expected := v_shift.opening_cash + v_cash_sales + v_movements;
    update public.cash_shifts set status='closed', closed_by=auth.uid(), closed_at=now(), counted_cash=p_counted_cash,
        expected_cash=v_expected, difference=p_counted_cash-v_expected, notes=nullif(left(trim(coalesce(p_notes,'')),500),'')
    where id=v_shift.id returning * into v_shift;
    return to_jsonb(v_shift);
end; $$;

create or replace function public.register_pos_payment(p_order_id bigint, p_payment_method text, p_amount numeric, p_tip numeric default 0)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype; v_shift_id uuid; v_paid numeric; v_methods integer;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or v_order.order_source <> 'pos' then raise exception 'Cuenta no encontrada'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'close_accounts') then raise exception 'Solo caja puede cobrar'; end if;
    if v_order.status='cancelado' or v_order.payment_status='approved' then raise exception 'La cuenta no admite pagos'; end if;
    if p_payment_method not in ('cash','transfer','card_terminal') or p_amount <= 0 or coalesce(p_tip,0) < 0 then raise exception 'Pago invalido'; end if;
    select id into v_shift_id from public.cash_shifts where restaurant_id=v_order.restaurant_id and status='open';
    select coalesce(sum(amount),0) into v_paid from public.order_payments where order_id=p_order_id;
    if p_amount > v_order.total-v_paid+0.01 then raise exception 'El abono supera el saldo pendiente'; end if;
    insert into public.order_payments(order_id,restaurant_id,shift_id,payment_method,amount,tip_amount,received_by)
    values(p_order_id,v_order.restaurant_id,v_shift_id,p_payment_method,p_amount,coalesce(p_tip,0),auth.uid());
    select coalesce(sum(amount),0), count(distinct payment_method) into v_paid,v_methods from public.order_payments where order_id=p_order_id;
    update public.orders set tip_total=(select coalesce(sum(tip_amount),0) from public.order_payments where order_id=p_order_id),
        payment_status=case when v_paid>=total then 'approved' else 'pending' end,
        payment_method=case when v_methods>1 then 'mixed' else p_payment_method end
    where id=p_order_id returning * into v_order;
    insert into public.order_audit_logs(order_id,restaurant_id,action,details,actor_id)
    values(p_order_id,v_order.restaurant_id,'payment',jsonb_build_object('method',p_payment_method,'amount',p_amount,'tip',coalesce(p_tip,0)),auth.uid());
    return to_jsonb(v_order)||jsonb_build_object('paid_total',v_paid,'remaining',greatest(v_order.total-v_paid,0));
end; $$;

create or replace function public.append_pos_order_items(p_order_id bigint, p_items jsonb, p_notes text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype; v_item jsonb; v_product public.products%rowtype; v_qty integer; v_added jsonb:='[]'::jsonb; v_total numeric:=0;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or v_order.order_source<>'pos' or v_order.payment_status='approved' or v_order.status='cancelado' then raise exception 'La cuenta no esta abierta'; end if;
    if exists(select 1 from public.order_payments where order_id=p_order_id) then raise exception 'No se pueden agregar productos despues de iniciar el cobro'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'create_orders') then raise exception 'Sin permiso para agregar productos'; end if;
    if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)<1 then raise exception 'Agrega productos'; end if;
    for v_item in select value from jsonb_array_elements(p_items) loop
        v_qty := (v_item->>'qty')::integer;
        select * into v_product from public.products where id::text=v_item->>'id' and restaurant_id=v_order.restaurant_id and is_available;
        if not found or v_qty<1 or v_qty>50 then raise exception 'Producto o cantidad invalida'; end if;
        v_added:=v_added||jsonb_build_array(jsonb_build_object('id',v_product.id,'nombre',v_product.name,'price',v_product.price,'qty',v_qty,'station_id',v_product.kitchen_station_id));
        v_total:=v_total+v_product.price*v_qty;
    end loop;
    update public.orders set items=items||v_added,total=total+v_total,notes=coalesce(nullif(left(trim(coalesce(p_notes,'')),500),''),notes),status='pendiente'
    where id=p_order_id returning * into v_order;
    insert into public.order_audit_logs(order_id,restaurant_id,action,details,actor_id) values(p_order_id,v_order.restaurant_id,'items_added',jsonb_build_object('items',v_added,'amount',v_total),auth.uid());
    return to_jsonb(v_order);
end; $$;

create or replace function public.transfer_pos_order(p_order_id bigint, p_table_id bigint, p_waiter_id uuid default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype; v_waiter_name text;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or v_order.order_source<>'pos' or v_order.payment_status='approved' then raise exception 'Cuenta no disponible'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'close_accounts') then raise exception 'Solo caja puede transferir cuentas'; end if;
    if p_table_id is not null and not exists(select 1 from public.restaurant_tables where id=p_table_id and restaurant_id=v_order.restaurant_id and is_active) then raise exception 'Mesa invalida'; end if;
    if p_waiter_id is not null then select full_name into v_waiter_name from public.profiles where id=p_waiter_id; end if;
    if p_waiter_id is not null and not exists(select 1 from public.restaurant_staff where restaurant_id=v_order.restaurant_id and user_id=p_waiter_id and is_active and can_create_orders) then raise exception 'Mesero invalido'; end if;
    update public.orders set table_id=p_table_id,service_type=case when p_table_id is null then 'pickup' else 'dine_in' end,
        created_by=coalesce(p_waiter_id,created_by),waiter_name=coalesce(v_waiter_name,waiter_name)
    where id=p_order_id returning * into v_order;
    insert into public.order_audit_logs(order_id,restaurant_id,action,details,actor_id) values(p_order_id,v_order.restaurant_id,'transferred',jsonb_build_object('table_id',p_table_id,'waiter_id',p_waiter_id),auth.uid());
    return to_jsonb(v_order);
end; $$;

create or replace function public.split_pos_order(p_order_id bigint, p_items jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype; v_new public.orders%rowtype; v_item jsonb; v_requested integer; v_original integer; v_selected jsonb:='[]'::jsonb; v_remaining jsonb:='[]'::jsonb; v_split_total numeric:=0;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or v_order.order_source<>'pos' or v_order.payment_status='approved' then raise exception 'Cuenta no disponible'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'close_accounts') then raise exception 'Solo caja puede dividir cuentas'; end if;
    if v_order.discount_total>0 then raise exception 'Divide la cuenta antes de aplicar un cupon'; end if;
    if exists(select 1 from public.order_payments where order_id=p_order_id) then raise exception 'Divide la cuenta antes de registrar abonos'; end if;
    if jsonb_typeof(p_items)<>'array' then raise exception 'Seleccion invalida'; end if;
    for v_item in select value from jsonb_array_elements(v_order.items) loop
        v_original:=coalesce((v_item->>'qty')::integer,0);
        select coalesce(sum((x->>'qty')::integer),0) into v_requested from jsonb_array_elements(p_items) x where x->>'id'=v_item->>'id';
        if v_requested<0 or v_requested>v_original then raise exception 'Cantidad invalida para %',v_item->>'nombre'; end if;
        if v_requested>0 then
            v_selected:=v_selected||jsonb_build_array(v_item||jsonb_build_object('qty',v_requested));
            v_split_total:=v_split_total+((v_item->>'price')::numeric*v_requested);
        end if;
        if v_original-v_requested>0 then v_remaining:=v_remaining||jsonb_build_array(v_item||jsonb_build_object('qty',v_original-v_requested)); end if;
    end loop;
    if jsonb_array_length(v_selected)=0 or jsonb_array_length(v_remaining)=0 then raise exception 'La division debe dejar productos en ambas cuentas'; end if;
    update public.orders set items=v_remaining,total=greatest(total-v_split_total,0) where id=p_order_id returning * into v_order;
    insert into public.orders(customer_id,restaurant_id,restaurant_name,items,total,notes,status,payment_method,payment_status,order_source,service_type,table_id,created_by,waiter_name,inventory_deducted)
    values(v_order.customer_id,v_order.restaurant_id,v_order.restaurant_name,v_selected,v_split_total,v_order.notes,v_order.status,'cash','pending','pos',v_order.service_type,v_order.table_id,v_order.created_by,v_order.waiter_name,v_order.inventory_deducted)
    returning * into v_new;
    insert into public.order_audit_logs(order_id,restaurant_id,action,details,actor_id) values(p_order_id,v_order.restaurant_id,'split',jsonb_build_object('new_order_id',v_new.id,'amount',v_split_total),auth.uid());
    return jsonb_build_object('original_order',to_jsonb(v_order),'new_order',to_jsonb(v_new));
end; $$;

create or replace function public.cancel_pos_order(p_order_id bigint, p_reason text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or v_order.order_source<>'pos' then raise exception 'Cuenta no encontrada'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'close_accounts') then raise exception 'Solo caja o propietario pueden cancelar'; end if;
    if char_length(trim(coalesce(p_reason,'')))<4 then raise exception 'Indica el motivo de cancelacion'; end if;
    if exists(select 1 from public.order_payments where order_id=p_order_id) then raise exception 'Una cuenta con pagos requiere devolucion administrativa'; end if;
    update public.orders set status='cancelado',cancelled_reason=left(trim(p_reason),300),closed_at=now() where id=p_order_id returning * into v_order;
    insert into public.order_audit_logs(order_id,restaurant_id,action,reason,actor_id) values(p_order_id,v_order.restaurant_id,'cancelled',v_order.cancelled_reason,auth.uid());
    return to_jsonb(v_order);
end; $$;

create or replace function public.apply_order_coupon(p_order_id bigint, p_code text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype; v_coupon public.coupons%rowtype; v_discount numeric;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found or not public.has_restaurant_permission(v_order.restaurant_id,'close_accounts') then raise exception 'Cuenta no disponible'; end if;
    if v_order.payment_status='approved' then raise exception 'La cuenta ya fue pagada'; end if;
    select * into v_coupon from public.coupons where restaurant_id=v_order.restaurant_id and upper(code)=upper(trim(p_code)) and is_active
      and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now());
    if not found then raise exception 'Cupon invalido o vencido'; end if;
    v_discount:=case when v_coupon.discount_type='percent' then round((v_order.total+v_order.discount_total)*least(v_coupon.discount_value,100)/100,2) else least(v_coupon.discount_value,v_order.total+v_order.discount_total) end;
    update public.orders set total=greatest(total+discount_total-v_discount,0),discount_total=v_discount where id=p_order_id returning * into v_order;
    insert into public.order_audit_logs(order_id,restaurant_id,action,details,actor_id) values(p_order_id,v_order.restaurant_id,'coupon',jsonb_build_object('code',v_coupon.code,'discount',v_discount),auth.uid());
    return to_jsonb(v_order);
end; $$;

create or replace function public.adjust_inventory(p_ingredient_id uuid, p_quantity numeric, p_type text, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_ingredient public.ingredients%rowtype;
begin
    select * into v_ingredient from public.ingredients where id=p_ingredient_id for update;
    if not found or v_ingredient.restaurant_id<>auth.uid() then raise exception 'Ingrediente no encontrado'; end if;
    if p_quantity=0 or p_type not in ('purchase','adjustment','waste') then raise exception 'Movimiento invalido'; end if;
    update public.ingredients set stock=greatest(stock+p_quantity,0),updated_at=now() where id=p_ingredient_id returning * into v_ingredient;
    insert into public.inventory_movements(restaurant_id,ingredient_id,movement_type,quantity,reason,created_by)
    values(v_ingredient.restaurant_id,p_ingredient_id,p_type,p_quantity,left(p_reason,200),auth.uid());
    return to_jsonb(v_ingredient);
end; $$;

create or replace function public.set_product_availability(p_product_id uuid, p_available boolean)
returns void language plpgsql security definer set search_path = '' as $$
declare v_restaurant_id uuid;
begin
    select restaurant_id into v_restaurant_id from public.products where id=p_product_id;
    if not found or not public.has_restaurant_permission(v_restaurant_id,'view_kitchen') then raise exception 'Sin permiso para cambiar disponibilidad'; end if;
    update public.products set is_available=p_available where id=p_product_id;
end; $$;

create or replace function public.list_available_waiters(p_restaurant_id uuid)
returns table(user_id uuid, full_name text, staff_role text) language plpgsql security definer set search_path = '' as $$
begin
    if not public.has_restaurant_permission(p_restaurant_id,'close_accounts') then raise exception 'Sin permiso de caja'; end if;
    return query select s.user_id,p.full_name,s.staff_role from public.restaurant_staff s join public.profiles p on p.id=s.user_id
      where s.restaurant_id=p_restaurant_id and s.is_active and s.can_create_orders order by p.full_name;
end; $$;

create or replace function public.deduct_order_inventory()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_item jsonb; v_recipe record; v_qty numeric;
begin
    if new.status='preparando' and old.status is distinct from 'preparando' and not new.inventory_deducted then
        for v_item in select value from jsonb_array_elements(new.items) loop
            v_qty:=coalesce((v_item->>'qty')::numeric,0);
            for v_recipe in select r.ingredient_id,r.quantity from public.product_recipes r where r.product_id::text=v_item->>'id' loop
                update public.ingredients set stock=stock-(v_recipe.quantity*v_qty),updated_at=now() where id=v_recipe.ingredient_id;
                insert into public.inventory_movements(restaurant_id,ingredient_id,movement_type,quantity,reason,order_id)
                values(new.restaurant_id,v_recipe.ingredient_id,'sale',-(v_recipe.quantity*v_qty),'Consumo por pedido',new.id);
            end loop;
        end loop;
        new.inventory_deducted:=true;
    end if;
    return new;
end; $$;
drop trigger if exists deduct_order_inventory on public.orders;
create trigger deduct_order_inventory before update of status on public.orders for each row execute function public.deduct_order_inventory();

create or replace function public.sync_order_station_statuses()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_item jsonb; v_station_id bigint; v_key text;
begin
    for v_item in select value from jsonb_array_elements(new.items) loop
        select kitchen_station_id into v_station_id from public.products where id::text=v_item->>'id';
        v_key:=coalesce(v_station_id::text,'general');
        insert into public.order_station_statuses(order_id,restaurant_id,station_key,kitchen_station_id,status)
        values(new.id,new.restaurant_id,v_key,v_station_id,'pendiente') on conflict(order_id,station_key) do nothing;
    end loop;
    return new;
end; $$;
drop trigger if exists sync_order_station_statuses on public.orders;
create trigger sync_order_station_statuses after insert or update of items on public.orders for each row execute function public.sync_order_station_statuses();

insert into public.order_station_statuses(order_id,restaurant_id,station_key,kitchen_station_id,status)
select o.id,o.restaurant_id,'general',null,o.status from public.orders o
where o.status in ('pendiente','preparando','listo')
on conflict(order_id,station_key) do nothing;

create or replace function public.update_kitchen_station_status(p_order_id bigint, p_station_key text, p_status text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_station public.order_station_statuses%rowtype; v_order_status text;
begin
    select * into v_station from public.order_station_statuses where order_id=p_order_id and station_key=p_station_key for update;
    if not found then raise exception 'Estacion de la comanda no encontrada'; end if;
    if not public.has_restaurant_permission(v_station.restaurant_id,'view_kitchen') then raise exception 'Sin permiso de cocina'; end if;
    if (v_station.status='pendiente' and p_status<>'preparando') or (v_station.status='preparando' and p_status<>'listo') or (v_station.status='listo' and p_status<>'entregado') then raise exception 'Cambio de estado invalido'; end if;
    update public.order_station_statuses set status=p_status,updated_at=now() where order_id=p_order_id and station_key=p_station_key returning * into v_station;
    select case
      when bool_and(status='entregado') then 'entregado'
      when bool_and(status in ('listo','entregado')) then 'listo'
      when bool_or(status in ('preparando','listo','entregado')) then 'preparando'
      else 'pendiente' end into v_order_status
    from public.order_station_statuses where order_id=p_order_id;
    update public.orders set status=v_order_status,
      ready_at=case when v_order_status='listo' then coalesce(ready_at,now()) else ready_at end,
      delivered_at=case when v_order_status='entregado' then coalesce(delivered_at,now()) else delivered_at end,
      closed_at=case when v_order_status='entregado' then coalesce(closed_at,now()) else closed_at end
    where id=p_order_id;
    return to_jsonb(v_station)||jsonb_build_object('order_status',v_order_status);
end; $$;

-- Mantiene la vista general compatible: avanzar desde "Todas las estaciones"
-- avanza todas las estaciones de la orden al mismo estado.
create or replace function public.update_kitchen_order_status(p_order_id bigint, p_status text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_order public.orders%rowtype;
begin
    select * into v_order from public.orders where id=p_order_id for update;
    if not found then raise exception 'Pedido no encontrado'; end if;
    if not public.has_restaurant_permission(v_order.restaurant_id,'view_kitchen') then raise exception 'No tienes permiso para actualizar cocina'; end if;
    if p_status not in ('preparando','listo','entregado') then raise exception 'Estado invalido'; end if;
    if (v_order.status='pendiente' and p_status<>'preparando') or (v_order.status='preparando' and p_status<>'listo') or (v_order.status='listo' and p_status<>'entregado') then raise exception 'El cambio de estado no es valido'; end if;
    update public.order_station_statuses set status=p_status,updated_at=now() where order_id=p_order_id;
    update public.orders set status=p_status,
      ready_at=case when p_status='listo' then coalesce(ready_at,now()) else ready_at end,
      delivered_at=case when p_status='entregado' then coalesce(delivered_at,now()) else delivered_at end,
      closed_at=case when p_status='entregado' then coalesce(closed_at,now()) else closed_at end
    where id=p_order_id returning * into v_order;
    return to_jsonb(v_order);
end; $$;

revoke all on function public.open_cash_shift(uuid,numeric), public.add_cash_movement(uuid,text,numeric,text),
    public.close_cash_shift(uuid,numeric,text), public.register_pos_payment(bigint,text,numeric,numeric),
    public.append_pos_order_items(bigint,jsonb,text), public.transfer_pos_order(bigint,bigint,uuid),
    public.split_pos_order(bigint,jsonb), public.cancel_pos_order(bigint,text), public.apply_order_coupon(bigint,text),
    public.adjust_inventory(uuid,numeric,text,text), public.set_product_availability(uuid,boolean),
    public.list_available_waiters(uuid), public.update_kitchen_station_status(bigint,text,text) from public, anon;
grant execute on function public.open_cash_shift(uuid,numeric), public.add_cash_movement(uuid,text,numeric,text),
    public.close_cash_shift(uuid,numeric,text), public.register_pos_payment(bigint,text,numeric,numeric),
    public.append_pos_order_items(bigint,jsonb,text), public.transfer_pos_order(bigint,bigint,uuid),
    public.split_pos_order(bigint,jsonb), public.cancel_pos_order(bigint,text), public.apply_order_coupon(bigint,text),
    public.adjust_inventory(uuid,numeric,text,text), public.set_product_availability(uuid,boolean),
    public.list_available_waiters(uuid), public.update_kitchen_station_status(bigint,text,text) to authenticated;

commit;
