-- Eventos seguros en tiempo real para el marketplace de repartidores.
-- Ejecutar despues de 019_fix_delivery_cash_payment.sql.

begin;

create table if not exists public.delivery_marketplace_events (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    event_type text not null check (event_type in ('created','status_changed','claimed','payment_changed')),
    created_at timestamptz not null default now()
);

create index if not exists delivery_marketplace_events_created_idx
    on public.delivery_marketplace_events(created_at desc);

alter table public.delivery_marketplace_events enable row level security;
drop policy if exists "active_drivers_read_marketplace_events" on public.delivery_marketplace_events;
create policy "active_drivers_read_marketplace_events"
on public.delivery_marketplace_events for select to authenticated
using (
    exists (
        select 1 from public.delivery_drivers d
        where d.user_id=auth.uid() and d.status='active'
    )
);

create or replace function public.publish_delivery_marketplace_event()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_type text;
begin
    if new.service_type<>'delivery' then return new;end if;
    if tg_op='INSERT' then
        v_type:='created';
    elsif old.assigned_driver_id is distinct from new.assigned_driver_id then
        v_type:='claimed';
    elsif old.payment_status is distinct from new.payment_status then
        v_type:='payment_changed';
    elsif old.delivery_status is distinct from new.delivery_status then
        v_type:='status_changed';
    else
        return new;
    end if;
    insert into public.delivery_marketplace_events(order_id,event_type)
    values(new.id,v_type);
    return new;
end; $$;

drop trigger if exists publish_delivery_marketplace_event on public.orders;
create trigger publish_delivery_marketplace_event
after insert or update of delivery_status,assigned_driver_id,payment_status on public.orders
for each row execute function public.publish_delivery_marketplace_event();

grant select on public.delivery_marketplace_events to authenticated;

do $$
begin
    alter publication supabase_realtime add table public.delivery_marketplace_events;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter publication supabase_realtime add table public.delivery_drivers;
exception when duplicate_object then null;
end $$;

commit;
